# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'nanjj blog'
subtitle: ''
email: nanjj@cn.ibm.com
description: ''
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nanjj.github.io" # the base hostname & protocol for your site
codeurl: 'https://github.com/nanjj'

# Build settings
markdown: kramdown

navigation: 2
sections: [
    ['whoami', 'whoami'],
    ['idea', 'Idea'],
    ['tip', 'Tip'],
    ['story', 'Story'],
    ['learning', 'Learning'],
]

disqus_shortname: ''
google_analytics_id: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['jekyll-page', 'README.md']